# Generated by Django 5.0.4 on 2024-04-19 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='id_turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_escola.turma'),
        ),
    ]
