# Generated by Django 5.0.4 on 2024-04-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escola', '0002_alter_atividade_id_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='atividade_arquivos/'),
        ),
    ]
